---
title: "Culbertson_2010"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Culbertson argues for an analysis of French subject clitics as agreement markers, instead of syntactic arguments (see:De Cat), specifically in "European Colloquial French" (in contrast to "European Standard French"). She claims that Colloquial French is in the middle of a "continous cline" (Hopper & Traugott 1993), as opposed to a discrete change, of how subject clitics are treated.She posits French subject clitics on this cline by demonstrating the continous weakening from Old French strong subject pronouns to clitics to affixes (in Colloquial French). She claims that European French speakers have access to the two separate grammars of Colloquial and Standard French, which she uses to explain variation and optionality in the data. Although she does not claim assumptions from a particular framework, she appeals to Distributed Morphology (Halle & Marantz 1993) most often to give examples of how her hypotheses would function within a framework. She uses various evidence, including experiments (AJT), prosody analysis, crosslinguistic typology, and corpora analysis (child directed speech comes from the Lyon corpus [Demuth & Tremblay 2008] while adulted directed speech comes from the PFC Corpus [Phonologie du francais contemporain, Durand et al. 2002, 2005]).

Culbertson first examines a number of phenomena previously discussed in the literature, and positions them in relation to her current arguments. She examines: reduction of French clitics and lexical attachment, liaison and implications about attachment, "ne"-retention, inversion, wide- and narrow-scope of subject clitic in VP coordination, and complement clitics.  

She argues that the phonological reduction of French clitics is indicative of a high level of fusion between the element (the clitic) and the host (the verb). She argues that the clitic cannot be attached at the synactic level, because it can modify specific lexical items (eg: "je suis" /ʒøsɥi/ [ʃɥi]). This form is also not derived from a phonological rule because, according to her, no such rule exists. I am skeptical on this.

She then claims that liaison characteristics posit the clitic attachment at the word-level, as opposed to phrase-level (which would have indicated that it were a phonological clitic). However, I am unsure that I believe that liason is a word-level phenomenon (re:Nespor 1986).

Culbertson moves onto "ne"-retention, where she agrees that it is most logical to posit that it is not an affix. She finds that in Colloquial French, "ne" has a pattern of distrubtion with the subject DP and clitic. She analyzes the Lyon corpus and takes the percentage of ne-retention "by dividing the actual number of ne uses by the number of possible contexts for ne." "Ne" appears in decreasing frequency with: DP subject (83%) > No DP or subject clitic (14%) > Subject clitic (6%) > DP and subject clitic (7%) (remember that each percentage is individually out of 100%, not combined). "Ne", according to this data, is preferentially dropped when it would intervene between a subject clitic and verb. Crosslinguistically, she adds that some Friulian dialects show complementary distrubtion between agreement subuject clitics and negative markers. She goes on to use a likelihood-ratio statstic to compare her two-grammar model (where speakers have access to two separate grammars for Standard and Colloquial French) and a one-grammar model (like De Cat's). She finds that her model is statistically more likley, but given that it is much more flexible, I don't find this particularly groundbreaking or suprising; I do not believe that she gives enough evidence for why speakers would have two grammars, though, or examples of speakers who might have only one of those grammars (so it would be interesting to investigate heritage speakers of "Colloquial French"). I would be interested to look at "ne"-retention and subject clitics in other languages, like Picard and Friulian.

She then examines inversion in Colloquial French. She finds that inversion of the verb and subject clitic is "vanishingly rare", but inversion with a full subject DP and verb is fully available and the preferred strategy for WH-question formation (88% 46/52 tokens featuring inversion in the Lyon corpus). 

She looks at subject-clitic repetition in coordinated VPs. In Northern Italian languages, agreement clitics are obligatorily repeated. In Standard French, this is not the case for subject clitics; in Colloquial French, subject clitics cannot take wide scope for coordinated VPs (similarly high frequencies of repeated subject clitics in both the Lyon and PFC corpora).

She then looks at complement clitics (e.g. object, reflexive, and locative clitics). She poses the question of object-clitic climbing, as De Cat (2005) had, and positions the phenoemon within the cartographic framework (Cardinaletti & Shlonsky 2004), but does not provide anything novel to explain this.

Culbertson then examines a number of features on subject doubling in French. She mentions that Pied Noir French (Roberge 1990) and Picard (Auger 2003) both allow subject doubling, but it is unknown if Standard or Colloquial French does. Although "Jean il parle" is possible, "personne (\*il) ne parle" convinces some that the first is left dislocation of "Jean", not true subject doubling. This is in contrast to Trentino and Fiorentino, which allows doubling of quantified subjects. Culbertson argues, conversely, that true subject doubling is allowed in Colloquial French through experimental evidence (prosody analyses and an AJT),as well as corpora analysis.

Her first experimental evidence comes from prosodic analysis of productions of left dislocation in French. She compares DP-subj, DP-subj+clitic, and DP-object constructions (eg: David(i) l(j)'a déjà invité vs David(i) il(i) déjà l(j)'a invité vs David(i) il(j) l(j)'a déjà invité. She finds that speakers do not differentiate productively between DP-subj and DP-subj+clitic in terms of F0 (the main factor for left dislocation in French), but they do for DP-obj. This indicates to her that only DP-objs are left dislocated. Furthermore, only the DP-obj features optional resyllabification and pause, whereas in cases of DP-subj+clitic feature resyllabification more frequently (e.g. [da.vi.di.la]).

According to De Cat (2004), DP subjects with a focus interpretation cannot cooccur with subject clitics. Culbertson argues against this based on De Cat's experimental design and with results from Culbertson's own AJT. Her results agree with De Cat in that DP-subj+clitic is less acceptable when the subject is narrowly focused or indefinite, but she finds that it is acceptable in topic contexts and broad-focus contexts, "where the subject is just one part of the focused verb phrase." Since doubled subjects appear in a focused context, where the two elements should be competing for a single theta role, Culbertson argues that the subject clitic must be an agreement marker, not a syntactic argument.

Like Gotowski (2005), Culbertson finds in the Lyon corpus that subject doubling in children is extremely common. In the PFC corpus (adult-directed speech), she finds that age has an effect; those younger than 35 years old are more likely to produce subject-doubling (almost 70%), while those older are less likely (50%). Subject doubling with strong pronouns, however, were near ceiliing across speakers.

Culbertson combats the argument that agreement is obligatorily overt. She positions French within a similar framework to Poletto (2000) who created a hierarchy of possible patterns of subject doubling in Norther Italian language: strong pronouns > DPs > quantified phrases > WH-variables. That is to say, if a language allows doubled subjects for WH-variables, it will obligatorily allow subject doubling for the other three categories; if it allows it for quantified phrases, it will be allowed for the lower two, and so on. French would then be positioned on the lowest tier, where strong pronouns are the only elements that obligatorily feature subject doubling. This is in line with the following exchange: "Qui a appelé Jean?" "Moi \*(je) l'ai appelé." Here, even though "Moi" is narrowly focused, and should not appear with a doubled subject, it obligatorily does.

She finally appeals to the Matching Hypothesis (Suñer 1988, 1992) to constrain subject doubling in Colloquial French, explaining that "an agreement marker and its argument controller must match featurally." Subject clitics, then have phi features for person, gender, and number, as well as [+definite] and [+accessible]. Subject doubling will only occur if the DP-subj is [+definite] and [+accessible], explaining why indefinites and WH-words would not surface with doubled subjects.

She concludes by explaining that the consequence of this analysis is that Colloquial French would be treated like an NSL. She defends her position briefly by explaining that Colloquial French does exhibit some features of NSLs (null nonreferential subjects, postverbal subjects, and 'that'-trace effect violations), but some of these features can also be found in uncontested non-NSLs, like English.