---
title: "Poletto&Tortora 1993"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Poletto & Tortora describe the subject clitics of languages found in northern Italy and southern France.

A langauge Paduan features a clitic "a" that is used to mark the entire sentence as new information, as well as inflectionally marking fist person singular and plural and second person plural. Beninca 1983, the one who describes this phenomenon, proposed that the clitic is found in Topic head in the left periphery of the clause.

The authors explain that common diagnostics used by others to determine if a language like French has subject clitics as inflectional markers are often misleading. There are many NI langauges that indisputibly of this type, but they do not perform as one might expect under diagnostics because of the variety even among these languages. Diagnostics include the impoverishment of a personal subject clitic system, but this is not universal. Another, if negation can come between the clitic and verb, but this presupposes that all negation is of the same type, which is not the case. VP-cooridnation is another test, but it is again inadequate; there are northern Italian languages that do not repeat the clitic in each conjuncted clause, yet they are shown to be heads.

The authors then typologically classify the subject clitics available to the described languages. Renzi & Vanelli (1983) propose an entailment relationship in the occurence of subject clitics across these languages in the following order, where each one entails the one to the left: person > number > deictic > invariable. For each type, they describe various, specific properties that group the languages' uses of these types together. French can be compared to these. Culbertson 2010 had compared French subject doubling to a similar entailment chain proposed by Poletto 2000.

De Cat 2005 proposed that subject clitics in French may serve a pragmatic function in cases of subject doubling, indicating that the subject DP is [-focus] and [+topic]. Poletto & Tortora explain that some NI languages display just this type of behavior. The subject clitic can only occur if the subject is a topic, and this environment is apparently the first place where subject clitic doubling occurs. Culbertson 2010 suggested that the subject's definiteness or specificity played a role in licensing subject doubling, which is recapitulated here. The authors do not, however, specify any languages in which this occurs.

